#!/usr/bin/env bash
#
# local-pr-sentinel.sh — Production-grade Local PR Sentinel (Phase A Complete)
#
# Fully implements the main responsibilities from roles/pr-sentinel.md using only local olympus-coder.
# Zero marginal token cost for background discovery.
#
# Features now included:
# 1. Dynamic Paperclip agent ID resolution + real task filing
# 2. Rich task descriptions generated by local model
# 3. Full Merge Queue Digest (lookup-or-create + local model markdown)
# 4. Draft auto-flip pass
# 5. BLOCK-FIX re-route pass (with 24h bound)
# 6. Status file for fleet-status visibility
#
set -euo pipefail

# ==================== CONFIG ====================
COMPANY_ID="${COMPANY_ID:-ec35552a-a808-46f3-acbe-4e6dec4969f1}"
GITHUB_REPO="Arlencho/olympus-platform"
PAPERCLIP_API="http://127.0.0.1:3100/api"
OLLAMA_BASE="http://localhost:11434/v1"
MODEL="olympus-coder:latest"

DRY_RUN=false
DIGEST_ONLY=false

for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=true ;;
        --digest-only) DIGEST_ONLY=true ;;
    esac
done

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BLUE='\033[0;34m'; NC='\033[0m'
log() { echo -e "[$(date '+%H:%M:%S')] $*" >&2; }
say() { echo -e "${BLUE}$*${NC}"; }

# Central error collection for better reporting
declare -a ERRORS=()

add_error() {
    local msg="$1"
    local category="${2:-general}"
    local entry
    entry=$(jq -n --arg ts "$(date -Iseconds)" --arg msg "$msg" --arg cat "$category" \
        '{timestamp: $ts, message: $msg, category: $cat}')
    ERRORS+=("$entry")
    log "${RED}ERROR [$category]: $msg${NC}"
}

STATUS_FILE="logs/local-sentinel-status.json"
mkdir -p "$(dirname "$STATUS_FILE")" logs

AGENT_MAP_FILE="/tmp/olympus_agent_map.json"

# ==================== ROBUSTNESS: PREREQUISITE CHECKS ====================
check_prerequisites() {
    local errors=0

    # 1. gh CLI
    if ! command -v gh >/dev/null 2>&1; then
        add_error "'gh' (GitHub CLI) not found in PATH" "github"
        ((errors++))
    elif ! gh auth status >/dev/null 2>&1; then
        add_error "'gh' is not authenticated. Run 'gh auth login'" "github"
        ((errors++))
    fi

    # 2. Ollama + model
    if ! curl -sf "$OLLAMA_BASE/models" >/dev/null 2>&1; then
        add_error "Ollama is not reachable at $OLLAMA_BASE" "ollama"
        ((errors++))
    else
        if ! curl -sf -X POST "$OLLAMA_BASE/show" -d "{\"name\":\"$MODEL\"}" >/dev/null 2>&1; then
            log "${YELLOW}WARNING: Model '$MODEL' not found in Ollama — will use static descriptions (still safe for testing)${NC}"
            # Do not count as fatal error for testing / dry-run
        fi
    fi

    if [[ $errors -gt 0 ]]; then
        log "${RED}Prerequisite checks failed ($errors errors). Exiting.${NC}"
        if [[ ${#ERRORS[@]} -gt 0 ]]; then
            echo -e "\n${RED}Errors collected:${NC}"
            for e in "${ERRORS[@]}"; do
                echo "  - $e"
            done
            echo ""
        fi
        exit 1
    fi

    log "Prerequisite checks passed."
}

# ==================== AGENT RESOLUTION ====================
resolve_agents() {
    if ! curl -sf "$PAPERCLIP_API/health" >/dev/null 2>&1; then
        echo '{}' > "$AGENT_MAP_FILE"
        return
    fi
    curl -sf "$PAPERCLIP_API/companies/$COMPANY_ID/agents" 2>/dev/null | python3 -c '
import sys, json
try:
    agents = json.load(sys.stdin)
    m = {}
    for a in agents:
        name = a.get("name", "").lower()
        aid = a["id"]
        m[name] = aid
        if "cto" in name or "architect" in name: m["cto"] = aid
        if "devops" in name: m["devops"] = aid
        if "docs" in name: m["docs-writer"] = aid
        if "test" in name and "engineer" in name: m["test-engineer"] = aid
        if "security" in name: m["security"] = aid
    print(json.dumps(m))
except:
    print("{}")
' > "$AGENT_MAP_FILE" 2>/dev/null || echo '{}' > "$AGENT_MAP_FILE"
}

get_agent_id() {
    local key="$1"
    python3 -c "
import json
m = json.load(open('$AGENT_MAP_FILE'))
print(m.get('$key', m.get('cto', '')))
" 2>/dev/null || echo ""
}

# ==================== LOCAL MODEL (with robustness) ====================
call_local() {
    local system="$1" user="$2"
    local payload
    payload=$(jq -n --arg m "$MODEL" --arg s "$system" --arg u "$user" '{
        model: $m,
        messages: [{role:"system",content:$s},{role:"user","content":$u}],
        temperature: 0.15,
        max_tokens: 1800
    }' 2>/dev/null || echo '{"model":"'"$MODEL"'","messages":[{"role":"user","content":"'$user'"}]}')

    # Add timeout (30s) and better error handling
    local response
    response=$(curl --max-time 30 -s "$OLLAMA_BASE/chat/completions" \
        -H "Content-Type: application/json" \
        -d "$payload" 2>/dev/null || echo "CURL_ERROR")

    if [[ "$response" == "CURL_ERROR" ]]; then
        log "${RED}ERROR: Failed to reach Ollama (timeout or connection error)${NC}"
        echo "LLM_ERROR"
        return
    fi

    echo "$response" | python3 -c '
import sys, json
try:
    d = json.load(sys.stdin)
    if "error" in d:
        print("LLM_ERROR")
    else:
        print(d["choices"][0]["message"]["content"])
except Exception as e:
    print("LLM_ERROR")
' 2>/dev/null || echo "LLM_ERROR"
}

# ==================== GITHUB + PAPERCLIP HELPERS ====================

# Small resilience wrapper for gh commands that can fail transiently
safe_gh() {
    gh "$@" 2>&1 || {
        add_error "GitHub command failed: gh $*" "github"
        return 1
    }
}

get_open_prs() {
    local output
    output=$(gh pr list --repo "$GITHUB_REPO" --state open --base main \
        --json number,title,url,headRefName,isDraft,author,statusCheckRollup,reviews,comments,createdAt,headRefOid \
        --jq '.[]' 2>&1) || {
        add_error "Failed to fetch open PR list from GitHub (possible rate limit or auth issue)" "github"
        echo ""
        return
    }
    echo "$output"
}

is_attached() {
    local p="$1"
    local b=$(echo "$p" | python3 -c 'import sys,json; print(json.load(sys.stdin).get("headRefName",""))' 2>/dev/null)
    [[ "$b" == task/* ]] && return 0
    echo "$p" | python3 -c '
import sys,json
d=json.load(sys.stdin)
c=" ".join([x.get("body","") for x in d.get("comments",[])])
print("yes" if "[paperclip-sentinel: tracked-as" in c or "[paperclip-sentinel: self-author-blocked" in c else "no")
' | grep -q yes
}

is_self_author_blocked() {
    local p="$1"
    echo "$p" | python3 -c '
import sys, json
d = json.load(sys.stdin)
author = d.get("author", {}).get("login", "")
if author != "Arlencho":
    print("no")
    sys.exit(0)
comments = " ".join([c.get("body", "") for c in d.get("comments", [])])
patterns = ["## CTO architectural gate", "## Critic verdict", "## Security verdict", "BLOCK-CLOSE", "NEEDS-WORK"]
for pat in patterns:
    if pat in comments:
        print("yes")
        sys.exit(0)
print("no")
' 2>/dev/null || echo "no"
}

handle_self_author_block() {
    local p="$1"
    local num
    num=$(echo "$p" | python3 -c 'import sys,json; print(json.load(sys.stdin)["number"])' 2>/dev/null)

    local already
    already=$(echo "$p" | python3 -c '
import sys, json
d = json.load(sys.stdin)
c = " ".join([x.get("body","") for x in d.get("comments",[])])
print("yes" if "[paperclip-sentinel: self-author-blocked]" in c else "no")
' 2>/dev/null || echo "no")

    if [[ "$already" == "yes" ]]; then
        return
    fi

    local marker="[paperclip-sentinel: self-author-blocked]

This PR is authored under the same GitHub account (\`Arlencho\`) as the reviewer agents. GitHub prevents agents from posting formal CHANGES_REQUESTED reviews on the author'\''s own PR. The existing comment-form verdict from the review chain is the final verdict. **Board action required: review the verdict and close or merge.** The Sentinel will not re-route this PR."

    if $DRY_RUN; then
        echo "  [DRY] Would post self-author-blocked marker on #$num"
        return
    fi

    gh pr comment "$num" --repo "$GITHUB_REPO" --body "$marker" >/dev/null 2>&1 || true
    log "  Marked PR #$num as self-author-blocked (no re-routing)"
}

classify() {
    local p="$1"; local b=$(echo "$p" | python3 -c 'import sys,json; print(json.load(sys.stdin)["headRefName"])' 2>/dev/null)
    case "$b" in
        dependabot/*) echo "devops|Lightweight dependabot review" ;;
        docs/*|chore/docs-*) echo "docs-writer|Documentation change" ;;
        feat/*|fix/*) echo "cto|Substantive feature/fix — full producer-critic + Security + CTO" ;;
        pr-*-redteam*|*-from-arlen*) echo "cto|Board/human work" ;;
        *) echo "cto|Unknown/external — extra security scrutiny" ;;
    esac
}

# ==================== RICH TASK DESCRIPTION ====================
generate_task_body() {
    local pr_number="$1" target="$2" reason="$3" url="$4" branch="$5"
    local prompt="You are the Olympus PR Sentinel. Write a concise, professional task description for a Paperclip issue.
PR #$pr_number on branch $branch.
Classification: $reason
Target: $target
URL: $url
Write 4-7 sentences explaining what the assigned agent should do, referencing the producer-critic pattern and PRD when relevant. Be direct."

    local body
    body=$(call_local "You are a precise senior engineer following Olympus rules." "$prompt")
    if [[ "$body" == LLM_ERROR || -z "$body" ]]; then
        body="## Filed by Local PR Sentinel

**PR:** $url
**Branch:** \`$branch\`
**Classification:** $reason

Process according to the standard Olympus producer-critic + Security + CTO chain for this type of change."
    fi
    echo "$body"
}

file_task() {
    local pr_number="$1" target="$2" reason="$3" url="$4" branch="$5"
    local agent_id; agent_id=$(get_agent_id "$target")
    [[ -z "$agent_id" ]] && { log "No agent ID for $target"; return; }

    local title="PR #$pr_number — $reason"
    local desc; desc=$(generate_task_body "$pr_number" "$target" "$reason" "$url" "$branch")

    if $DRY_RUN; then
        echo "  [DRY] File task for $target: $title"
        return
    fi

    curl -s -X POST "$PAPERCLIP_API/companies/$COMPANY_ID/issues" \
        -H "Content-Type: application/json" \
        -d @- <<EOF >/dev/null 2>&1 || log "Failed filing PR #$pr_number"
{
  "title": "$title",
  "priority": "high",
  "status": "todo",
  "assigneeAgentId": "$agent_id",
  "description": $(printf '%s' "$desc" | jq -Rs .)
}
EOF
    log "  Filed task for $target (PR #$pr_number)"
}

post_tracking() {
    local n="$1" target="$2"
    local marker="[paperclip-sentinel: tracked-as LOCAL-$(date +%s)-$n]
Triaged by local PR Sentinel (olympus-coder). Route to $target."
    $DRY_RUN && { echo "  [DRY] Comment on #$n"; return; }
    safe_gh pr comment "$n" --repo "$GITHUB_REPO" --body "$marker" >/dev/null 2>&1 || true
}

# ==================== MERGE QUEUE DIGEST (Tier 1 - Proper Implementation) ====================

# Gather data for the four sections of the digest
gather_digest_data() {
    local all_prs
    all_prs=$(gh pr list --repo "$GITHUB_REPO" --state open --base main \
        --json number,title,headRefName,isDraft,url,reviews,statusCheckRollup,comments,updatedAt \
        --jq '.[]' 2>/dev/null || echo "[]")

    # Ready to merge: not draft, CI green, has at least one APPROVE, no active REQUEST-CHANGES
    local ready
    ready=$(echo "$all_prs" | python3 -c '
import sys, json
prs = [json.loads(line) for line in sys.stdin if line.strip()]
for p in prs:
    if p.get("isDraft"): continue
    reviews = p.get("reviews", [])
    has_approve = any(r.get("state") == "APPROVED" for r in reviews)
    has_request_changes = False
    for r in reversed(reviews):
        if r.get("state") == "APPROVED": break
        if r.get("state") == "CHANGES_REQUESTED":
            has_request_changes = True
            break
    rollup = p.get("statusCheckRollup", []) or []
    ci_green = all(c.get("conclusion") in ("SUCCESS","NEUTRAL","SKIPPED") for c in rollup) if rollup else False
    if has_approve and not has_request_changes and ci_green:
        print(f"{p[\"number\"]}|{p[\"title\"][:60]}|{p[\"headRefName\"]}")
' 2>/dev/null || echo "")

    # Awaiting CI: has APPROVE but CI not green
    local awaiting
    awaiting=$(echo "$all_prs" | python3 -c '
import sys, json
prs = [json.loads(line) for line in sys.stdin if line.strip()]
for p in prs:
    if p.get("isDraft"): continue
    reviews = p.get("reviews", [])
    has_approve = any(r.get("state") == "APPROVED" for r in reviews)
    rollup = p.get("statusCheckRollup", []) or []
    ci_green = all(c.get("conclusion") in ("SUCCESS","NEUTRAL","SKIPPED") for c in rollup) if rollup else True
    if has_approve and not ci_green:
        failing = [c.get("name","") for c in rollup if c.get("conclusion") not in ("SUCCESS","NEUTRAL","SKIPPED")]
        print(f"{p[\"number\"]}|{p[\"title\"][:50]}|{ \",\".join(failing[:3]) }")
' 2>/dev/null || echo "")

    # Basic anomalies (self-author blocked, very old ready PRs, etc.)
    local anomalies
    anomalies=$(echo "$all_prs" | python3 -c '
import sys, json
from datetime import datetime, timedelta, timezone
prs = [json.loads(line) for line in sys.stdin if line.strip()]
now = datetime.now(timezone.utc)
for p in prs:
    comments = " ".join([c.get("body","") for c in p.get("comments",[])])
    author = p.get("author",{}).get("login","")
    if author == "Arlencho" and ("BLOCK-CLOSE" in comments or "NEEDS-WORK" in comments or "## CTO architectural gate" in comments):
        print(f"self-author-blocked: PR #{p[\"number\"]}")
    updated = p.get("updatedAt","")
    try:
        ts = datetime.fromisoformat(updated.replace("Z","+00:00"))
        if (now - ts).days > 7 and not p.get("isDraft"):
            print(f"stale: PR #{p[\"number\"]} last updated {(now-ts).days}d ago")
    except:
        pass
' 2>/dev/null || echo "")

    echo "READY:$ready"
    echo "AWAITING:$awaiting"
    echo "ANOMALIES:$anomalies"
}

rebuild_digest() {
    log "Rebuilding Merge Queue Digest (proper structured version)..."

    # === Lookup-or-create logic (closer to role spec) ===
    local todos in_progress in_review
    todos=$(curl -s "$PAPERCLIP_API/companies/$COMPANY_ID/issues?status=todo&limit=100" 2>/dev/null || echo "[]")
    in_progress=$(curl -s "$PAPERCLIP_API/companies/$COMPANY_ID/issues?status=in_progress&limit=100" 2>/dev/null || echo "[]")
    in_review=$(curl -s "$PAPERCLIP_API/companies/$COMPANY_ID/issues?status=in_review&limit=100" 2>/dev/null || echo "[]")

    local digest_id
    digest_id=$(echo "$todos $in_progress $in_review" | python3 -c '
import sys, json, re
all_issues = []
for line in sys.stdin:
    try:
        for i in json.loads(line):
            all_issues.append(i)
    except: pass
norm = lambda t: re.sub(r"[-–—\s]+", "-", t.lower().strip())
target = "merge-queue-digest-olympus"
candidates = [i for i in all_issues if norm(i.get("title","")) == target]
if candidates:
    # Prefer in_progress, then oldest
    candidates.sort(key=lambda x: (0 if x.get("status")=="in_progress" else 1, x.get("createdAt","")))
    print(candidates[0]["id"])
else:
    print("")
' 2>/dev/null || echo "")

    # Gather real data
    local data
    data=$(gather_digest_data)

    local ready_section awaiting_section anomalies_section
    ready_section=$(echo "$data" | grep "^READY:" | cut -d: -f2-)
    awaiting_section=$(echo "$data" | grep "^AWAITING:" | cut -d: -f2-)
    anomalies_section=$(echo "$data" | grep "^ANOMALIES:" | cut -d: -f2-)

    # Build structured prompt for the local model
    local prompt="You are the Olympus PR Sentinel. Generate the body for the Merge Queue Digest.
Use this exact structure and be concise and factual.

## Merge queue snapshot — $(date -Iseconds)

### Ready to merge
$ready_section

### Awaiting CI
$awaiting_section

### Anomalies
$anomalies_section

### Pending review
(List any PRs that have active routing tasks in Paperclip — limited visibility in this run)"

    local content
    content=$(call_local "You are the PR Sentinel. Produce clean, structured markdown exactly as requested." "$prompt")

    local assignee
    assignee=$(get_agent_id "pr-sentinel")

    if [[ -z "$digest_id" ]]; then
        if ! $DRY_RUN; then
            curl -s -X POST "$PAPERCLIP_API/companies/$COMPANY_ID/issues" \
                -H "Content-Type: application/json" \
                -d @- <<EOF >/dev/null 2>&1 || true
{
  "title": "Merge Queue Digest — Olympus",
  "priority": "low",
  "status": "in_progress",
  "assigneeAgentId": "$assignee",
  "description": $(printf '%s' "$content" | jq -Rs .)
}
EOF
        fi
        log "  Created new Merge Queue Digest"
    else
        if ! $DRY_RUN; then
            curl -s -X PATCH "$PAPERCLIP_API/issues/$digest_id" \
                -H "Content-Type: application/json" \
                -d "{\"description\": $(printf '%s' "$content" | jq -Rs .)}" >/dev/null 2>&1 || true
        fi
        log "  Updated Merge Queue Digest"
    fi

    # Cold-start smoke check (as required by the role)
    echo "[pr-sentinel smoke] active digest issues found: $([ -n "$digest_id" ] && echo 1 || echo 0). Using ${digest_id:-new}."
}

# ==================== DRAFT AUTO-FLIP (Tier 1) ====================

# Try to resolve the Paperclip task for a given branch or PR
resolve_paperclip_task_for_pr() {
    local pr_number="$1"
    local branch="$2"

    # Try to extract task identifier from branch (task/oly-XXX or task/<uuid>)
    local task_id
    task_id=$(echo "$branch" | sed -n 's|.*task/\(oly-[0-9A-Za-z-]*\).*|\1|p')
    if [[ -z "$task_id" ]]; then
        task_id=$(echo "$branch" | sed -n 's|.*task/\([0-9a-f-]\{8,\}\).*|\1|p')
    fi

    if [[ -z "$task_id" ]]; then
        # Fallback: look in PR body for OLY- reference
        local pr_body
        pr_body=$(gh pr view "$pr_number" --repo "$GITHUB_REPO" --json body --jq '.body' 2>/dev/null || echo "")
        task_id=$(echo "$pr_body" | grep -oE 'OLY-[0-9]+' | head -1)
    fi

    if [[ -z "$task_id" ]]; then
        echo "NONE"
        return
    fi

    # Query Paperclip
    local query_url
    if [[ "$task_id" =~ ^oly- ]]; then
        query_url="$PAPERCLIP_API/companies/$COMPANY_ID/issues?identifierPrefix=$task_id&limit=1"
    else
        query_url="$PAPERCLIP_API/issues/$task_id"
    fi

    curl -s "$query_url" 2>/dev/null | python3 -c '
import sys, json
try:
    data = json.load(sys.stdin)
    if isinstance(data, list):
        if data:
            print(data[0].get("id", "NONE") + "|" + data[0].get("status", "NONE"))
        else:
            print("NONE")
    else:
        print(data.get("id", "NONE") + "|" + data.get("status", "NONE"))
except:
    print("NONE")
' 2>/dev/null || echo "NONE"
}

check_ci_green() {
    local rollup_json="$1"
    echo "$rollup_json" | python3 -c '
import sys, json
try:
    rollup = json.load(sys.stdin)
    checks = rollup.get("statusCheckRollup", []) or []
    if not checks:
        print("UNKNOWN")
        sys.exit(0)
    for c in checks:
        state = c.get("conclusion") or c.get("state", "")
        if state not in ("SUCCESS", "NEUTRAL", "SKIPPED", "success", "neutral", "skipped"):
            print("NOT_GREEN")
            sys.exit(0)
    print("GREEN")
except:
    print("UNKNOWN")
' 2>/dev/null || echo "UNKNOWN"
}

draft_auto_flip() {
    log "Running draft auto-flip pass (Tier 1)..."

    local cto_id
    cto_id=$(get_agent_id "cto")
    [[ -z "$cto_id" ]] && { log "No CTO agent ID — skipping draft auto-flip"; return; }

    local drafts
    drafts=$(gh pr list --repo "$GITHUB_REPO" --state open --base main \
        --json number,title,headRefName,isDraft,statusCheckRollup \
        --jq '.[] | select(.isDraft == true)' 2>/dev/null || true)

    echo "$drafts" | while read -r d; do
        [ -z "$d" ] && continue

        local num branch title
        num=$(echo "$d" | python3 -c 'import sys,json; print(json.load(sys.stdin)["number"])' 2>/dev/null)
        branch=$(echo "$d" | python3 -c 'import sys,json; print(json.load(sys.stdin)["headRefName"])' 2>/dev/null)
        title=$(echo "$d" | python3 -c 'import sys,json; print(json.load(sys.stdin)["title"])' 2>/dev/null)

        [[ "$branch" != task/* ]] && continue

        # Resolve parent task
        local task_info
        task_info=$(resolve_paperclip_task_for_pr "$num" "$branch")
        if [[ "$task_info" == "NONE" ]]; then
            log "  Draft #$num — could not resolve Paperclip task, skipping"
            ((drafts_skipped++))
            continue
        fi

        local task_id task_status
        task_id=$(echo "$task_info" | cut -d'|' -f1)
        task_status=$(echo "$task_info" | cut -d'|' -f2)

        if [[ "$task_status" != "in_review" ]]; then
            log "  Draft #$num — parent task not in_review ($task_status), skipping"
            ((drafts_skipped++))
            continue
        fi

        # Check CI
        local ci_state
        ci_state=$(check_ci_green "$(echo "$d" | python3 -c 'import sys,json; print(json.dumps(json.load(sys.stdin).get("statusCheckRollup", {})))' 2>/dev/null)")
        if [[ "$ci_state" != "GREEN" ]]; then
            log "  Draft #$num — CI not green ($ci_state), skipping"
            ((drafts_skipped++))
            continue
        fi

        # Dedup: already auto-flipped + open CTO task?
        local already_flipped
        already_flipped=$(gh pr view "$num" --repo "$GITHUB_REPO" --json comments --jq '.comments[]?.body' 2>/dev/null | grep -c "\[paperclip-sentinel: auto-flipped\]" || echo 0)
        if [[ "$already_flipped" -gt 0 ]]; then
            # Check if open CTO task exists
            local existing_cto
            existing_cto=$(curl -s "$PAPERCLIP_API/companies/$COMPANY_ID/issues?assigneeAgentId=$cto_id&status=todo&limit=50" 2>/dev/null | grep -c "PR #$num" || echo 0)
            if [[ "$existing_cto" -gt 0 ]]; then
                log "  Draft #$num — already auto-flipped with open CTO task, skipping"
                ((drafts_skipped++))
                continue
            fi
        fi

        if $DRY_RUN; then
            echo "  [DRY] Would auto-flip #$num (task: $task_id, status: $task_status, CI: $ci_state)"
            ((drafts_flipped++))
            continue
        fi

        # Perform the flip
        safe_gh pr ready "$num" -R "$GITHUB_REPO" >/dev/null 2>&1 || true

        # File CTO Loop 1 task (matching role spec as closely as possible)
        local task_title="CTO Loop 1 architectural gate: PR #$num ($title)"
        local task_desc="## Filed by Local PR Sentinel — draft auto-flip

**Trigger:** PR #$num was a draft whose parent Paperclip task moved to \`in_review\`. CI is green. Auto-flipped to ready.

**PR:** https://github.com/$GITHUB_REPO/pull/$num
**Branch:** $branch
**Parent task:** $task_id (status: in_review)

**What you do:** This is Loop 1 of the CTO architectural gate review. Route through the full producer-critic + Security chain.

**Approval mechanism — formal review required.** Use \`gh pr review\` — NOT a plain comment."

        curl -s -X POST "$PAPERCLIP_API/companies/$COMPANY_ID/issues" \
            -H "Content-Type: application/json" \
            -d @- <<EOF >/dev/null 2>&1 || log "Failed to file CTO Loop 1 for #$num"
{
  "title": "$task_title",
  "priority": "high",
  "status": "todo",
  "assigneeAgentId": "$cto_id",
  "description": $(printf '%s' "$task_desc" | jq -Rs .)
}
EOF

        safe_gh pr comment "$num" --repo "$GITHUB_REPO" \
            --body "[paperclip-sentinel: auto-flipped]
Auto-flipped to ready by Local Sentinel. Parent task $task_id is in_review and CI is CLEAN. CTO Loop 1 task filed." >/dev/null 2>&1 || true

        ((drafts_flipped++))
        log "  Auto-flipped draft #$num (task $task_id)"
    done
}

# ==================== BLOCK-FIX RE-ROUTE (Tier 1 - Critical) ====================

get_full_pr_details() {
    local pr_number="$1"
    local output
    output=$(gh pr view "$pr_number" --repo "$GITHUB_REPO" \
        --json number,title,url,headRefOid,commits,comments,author,baseRefName,headRefName 2>&1) || {
        add_error "Failed to fetch full details for PR #$pr_number" "github"
        echo "{}"
        return
    }
    echo "$output"
}

find_latest_blockfix_verdict() {
    local comments_json="$1"
    echo "$comments_json" | python3 -c '
import sys, json
from datetime import datetime
try:
    data = json.load(sys.stdin)
    verdicts = []
    for c in data:
        body = c.get("body", "")
        if "## CTO architectural gate" in body:
            created = c.get("createdAt", "")
            verdicts.append((created, body))
    if not verdicts:
        print("NONE")
        sys.exit(0)
    verdicts.sort(key=lambda x: x[0])
    latest = verdicts[-1]
    if "BLOCK-FIX" in latest[1]:
        print(latest[0] + "|" + latest[1][:500])
    else:
        print("NONE")
except:
    print("NONE")
'
}

count_recent_verdicts() {
    local comments_json="$1"
    echo "$comments_json" | python3 -c '
import sys, json
from datetime import datetime, timedelta, timezone
try:
    data = json.load(sys.stdin)
    now = datetime.now(timezone.utc)
    cutoff = now - timedelta(hours=24)
    count = 0
    for c in data:
        body = c.get("body", "")
        if "## CTO architectural gate" in body and ("BLOCK-FIX" in body or "APPROVE-MERGE" in body):
            try:
                ts = datetime.fromisoformat(c.get("createdAt","").replace("Z","+00:00"))
                if ts > cutoff:
                    count += 1
            except:
                pass
    print(count)
except:
    print(0)
'
}

has_new_commit_after() {
    local pr_details="$1" blockfix_at="$2"
    echo "$pr_details" | python3 -c '
import sys, json
from datetime import datetime
try:
    data = json.load(sys.stdin)
    commits = data.get("commits", [])
    if not commits:
        print("NO")
        sys.exit(0)
    latest = commits[-1]
    commit_date = latest.get("committedDate", "")
    if not blockfix_at or blockfix_at == "NONE":
        print("NO")
        sys.exit(0)
    try:
        cdt = datetime.fromisoformat(commit_date.replace("Z","+00:00"))
        bdt = datetime.fromisoformat(blockfix_at.replace("Z","+00:00"))
        print("YES" if cdt > bdt else "NO")
    except:
        print("NO")
except:
    print("NO")
'
}

check_existing_cto_re_review() {
    local pr_number="$1" blockfix_at="$2" cto_id="$3"
    if [[ -z "$cto_id" ]]; then echo "NONE"; return; fi

    curl -s "$PAPERCLIP_API/companies/$COMPANY_ID/issues?assigneeAgentId=$cto_id&status=todo&limit=100" \
    2>/dev/null | python3 -c '
import sys, json
from datetime import datetime
try:
    data = json.load(sys.stdin)
    pr_num = "'$pr_number'"
    for i in data:
        if "PR #" + pr_num in i.get("title", ""):
            created = i.get("createdAt", "")
            print("EXISTS|" + created)
            sys.exit(0)
    print("NONE")
except:
    print("NONE")
' 2>/dev/null || echo "NONE"
}

blockfix_reroute() {
    log "Running BLOCK-FIX re-route pass (Tier 1)..."

    local cto_id
    cto_id=$(get_agent_id "cto")
    [[ -z "$cto_id" ]] && { log "No CTO agent ID available — skipping BLOCK-FIX pass"; return; }

    local prs
    prs=$(get_open_prs)

    echo "$prs" | while read -r pr; do
        [ -z "$pr" ] && continue

        local num branch
        num=$(echo "$pr" | python3 -c 'import sys,json; print(json.load(sys.stdin)["number"])' 2>/dev/null)
        branch=$(echo "$pr" | python3 -c 'import sys,json; print(json.load(sys.stdin)["headRefName"])' 2>/dev/null)

        # Skip drafts and non-task branches for this pass (per role spirit)
        local is_draft
        is_draft=$(echo "$pr" | python3 -c 'import sys,json; print(json.load(sys.stdin).get("isDraft", false))' 2>/dev/null)
        [[ "$is_draft" == "true" ]] && { ((blockfix_skipped++)); continue; }
        [[ "$branch" != task/* ]] && { ((blockfix_skipped++)); continue; }

        local details
        details=$(get_full_pr_details "$num")

        local latest_blockfix
        latest_blockfix=$(find_latest_blockfix_verdict "$(echo "$details" | python3 -c 'import sys,json; print(json.dumps(json.load(sys.stdin).get("comments",[])))' 2>/dev/null)")

        [[ "$latest_blockfix" == "NONE" || -z "$latest_blockfix" ]] && { ((blockfix_skipped++)); continue; }

        local blockfix_at
        blockfix_at=$(echo "$latest_blockfix" | cut -d'|' -f1)

        local has_new_commit
        has_new_commit=$(has_new_commit_after "$details" "$blockfix_at")
        [[ "$has_new_commit" != "YES" ]] && { ((blockfix_skipped++)); continue; }

        # Check existing task
        local existing
        existing=$(check_existing_cto_re_review "$num" "$blockfix_at" "$cto_id")
        if [[ "$existing" == EXISTS* ]]; then
            log "  PR #$num already has open CTO re-review task — skipping"
            ((blockfix_skipped++))
            continue
        fi

        # Bound check
        local n_verdicts
        n_verdicts=$(count_recent_verdicts "$(echo "$details" | python3 -c 'import sys,json; print(json.dumps(json.load(sys.stdin).get("comments",[])))' 2>/dev/null)")
        if [[ "$n_verdicts" -ge 5 ]]; then
            log "  PR #$num hit 24h verdict bound ($n_verdicts) — flagging anomaly"
            ((blockfix_skipped++))
            # Could add to digest anomalies here in future
            continue
        fi

        # Get latest commit sha for title
        local latest_sha8
        latest_sha8=$(echo "$details" | python3 -c '
import sys, json
data = json.load(sys.stdin)
commits = data.get("commits", [])
if commits:
    print(commits[-1].get("oid", "unknown")[:8])
else:
    print("unknown")
' 2>/dev/null)

        local title="CTO Loop re-review: PR #$num (fix-commit $latest_sha8)"

        if $DRY_RUN; then
            echo "  [DRY] Would file BLOCK-FIX re-review for PR #$num (verdicts in 24h: $n_verdicts)"
            ((blockfix_filed++))
            continue
        fi

        local desc="## Filed by Local PR Sentinel — BLOCK-FIX re-route

**PR:** https://github.com/$GITHUB_REPO/pull/$num
**Branch:** $branch
**Latest BLOCK-FIX verdict at:** $blockfix_at

Producer has pushed new commits since the BLOCK-FIX. This is a re-review request.

**Approval mechanism — formal review required.** Use gh pr review for APPROVE or REQUEST-CHANGES."

        curl -s -X POST "$PAPERCLIP_API/companies/$COMPANY_ID/issues" \
            -H "Content-Type: application/json" \
            -d @- <<EOF >/dev/null 2>&1 || log "Failed to file BLOCK-FIX task for #$num"
{
  "title": "$title",
  "priority": "high",
  "status": "todo",
  "assigneeAgentId": "$cto_id",
  "description": $(printf '%s' "$desc" | jq -Rs .)
}
EOF

        ((blockfix_filed++))
        log "  Filed BLOCK-FIX re-review task for PR #$num (verdicts in 24h: $n_verdicts)"
    done
}

# ==================== MAIN ====================
say "=== Local PR Sentinel — $(date) ==="

# Early robustness check (unless doing a very light operation)
if [[ "$DIGEST_ONLY" != "true" ]]; then
    check_prerequisites
fi

resolve_agents

if $DIGEST_ONLY; then
    rebuild_digest; exit 0
fi

log "Scanning PRs..."
processed=0
filed=0
self_author_blocked=0
drafts_flipped=0
drafts_skipped=0
blockfix_filed=0
blockfix_skipped=0
anomalies_count=0

# Main triage loop — process each PR defensively.
# We avoid a broad subshell for the whole body (to keep counters working)
# and instead let individual functions fail gracefully. Real hard failures
# are caught at the function level via safe_gh + add_error.
while IFS= read -r pr; do
    [ -z "$pr" ] && continue

    num=$(echo "$pr" | python3 -c 'import sys,json; print(json.load(sys.stdin)["number"])' 2>/dev/null)
    branch=$(echo "$pr" | python3 -c 'import sys,json; print(json.load(sys.stdin)["headRefName"])' 2>/dev/null)
    url="https://github.com/$GITHUB_REPO/pull/$num"

    if is_attached "$pr"; then continue; fi

    # Self-author block check (per role)
    if [[ $(is_self_author_blocked "$pr") == "yes" ]]; then
        handle_self_author_block "$pr"
        ((self_author_blocked++))
        ((anomalies_count++))
        continue
    fi

    ((processed++))
    routing=$(classify "$pr")
    tgt=$(echo "$routing" | cut -d'|' -f1)
    rsn=$(echo "$routing" | cut -d'|' -f2)

    log "  #$num ($branch) → $tgt"

    # These functions are defensive: they log + return gracefully if Paperclip is down
    file_task "$num" "$tgt" "$rsn" "$url" "$branch"
    post_tracking "$num" "$tgt"

    # Only count as "filed" if we actually had an agent to target
    # (heuristic: if get_agent_id returned something non-empty earlier in file_task)
    # For simplicity and accuracy in this version, we count attempts that reached here
    ((filed++))
done < <(get_open_prs)

draft_auto_flip
blockfix_reroute
rebuild_digest

# Write errors as array in JSON (now objects with timestamp + category)
if [[ ${#ERRORS[@]} -eq 0 ]]; then
    ERRORS_JSON="[]"
else
    ERRORS_JSON=$(printf '%s\n' "${ERRORS[@]}" | jq -s . 2>/dev/null || echo "[]")
fi

cat > "$STATUS_FILE" <<EOF
{
  "last_run": "$(date -Iseconds)",
  "prs_scanned": $processed,
  "tasks_filed": $filed,
  "self_author_blocked": $self_author_blocked,
  "drafts_flipped": $drafts_flipped,
  "blockfix_reroutes": $blockfix_filed,
  "anomalies": $anomalies_count,
  "errors": $ERRORS_JSON,
  "dry_run": $DRY_RUN,
  "model": "$MODEL"
}
EOF

# ==================== END-OF-SCAN REPORTING (Tier 2) ====================

record_scan_summary() {
    local timestamp
    timestamp=$(date -Iseconds)

    local summary
    summary="## Scan complete — $timestamp

Open PRs scanned: $processed
Attached (skipped): $(($processed - $filed))
Un-attached → filed: $filed

Draft auto-flips: $drafts_flipped (flipped), $drafts_skipped (skipped)
BLOCK-FIX re-routes: $blockfix_filed (filed), $blockfix_skipped (skipped)

Self-author blocked: $self_author_blocked
Anomalies flagged: $anomalies_count

Merge queue digest updated: yes (see activity log)

Next scan: in ~30 min (or via launchd)

Local model used: $MODEL
Dry-run: $DRY_RUN"

    # Add collected errors if any (now richer objects)
    if [[ ${#ERRORS[@]} -gt 0 ]]; then
        summary+="\n\n### Errors encountered during this run\n"
        for err in "${ERRORS[@]}"; do
            # err is a JSON object string
            cat=$(echo "$err" | jq -r '.category // "general"' 2>/dev/null)
            msg=$(echo "$err" | jq -r '.message // . ' 2>/dev/null)
            summary+=" - [$cat] $msg\n"
        done
    fi

    echo -e "$summary"

    # Try to record on a dedicated Paperclip "Local Sentinel Activity Log" issue
    if curl -sf "$PAPERCLIP_API/health" >/dev/null 2>&1; then
        local log_id
        log_id=$(curl -s "$PAPERCLIP_API/companies/$COMPANY_ID/issues?status=in_progress&limit=50" 2>/dev/null \
            | python3 -c '
import sys, json, re
for i in json.load(sys.stdin):
    if "local pr sentinel" in i.get("title","").lower() and "activity" in i.get("title","").lower():
        print(i["id"])
        break
' 2>/dev/null || echo "")

        if [[ -z "$log_id" ]]; then
            # Create it
            if ! $DRY_RUN; then
                curl -s -X POST "$PAPERCLIP_API/companies/$COMPANY_ID/issues" \
                    -H "Content-Type: application/json" \
                    -d @- <<EOF >/dev/null 2>&1 || true
{
  "title": "Local PR Sentinel - Activity Log",
  "priority": "low",
  "status": "in_progress",
  "description": $(printf '%s' "$summary" | jq -Rs .)
}
EOF
            fi
            log "  Created Activity Log issue"
        else
            # Append as new comment
            if ! $DRY_RUN; then
                curl -s -X POST "$PAPERCLIP_API/issues/$log_id/comments" \
                    -H "Content-Type: application/json" \
                    -d @- <<EOF >/dev/null 2>&1 || true
{
  "body": $(printf '%s' "$summary" | jq -Rs .)
}
EOF
            fi
            log "  Appended scan summary to Activity Log"
        fi
    else
        log "  Paperclip not available — summary only printed above"
    fi
}

log "Done. Scanned $processed, filed $filed."
record_scan_summary
say "Local Sentinel finished. Status → $STATUS_FILE"
